### ISSUE TITLE
question about ESRI_Object_Detection/train.ipynb

### ISSUE THREAD

**Issue by liminghuiv** [kunwar31/ESRI_Object_Detection#1]
Hi @kunwar31 ,
Congratunations on your ESRI competition.
When I try to visualiza the augmentation: 
if visualize:
            imgs = seq.augment_images(imgs)
            imgs = np.array(imgs)
            boxes = np.array(boxes)
            yield imgs,boxes

I got: 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-20-f0f0ce1967df> in <module>()
      4 i = 0
      5 
----> 6 for imgs,boxes in augment_train_gen(train_gen, additional_augmentation=True, visualize=True):
      7     if i > skip_batches:
      8         fig=plt.figure(figsize=(24,96))

<ipython-input-19-3bf50f6a7ff8> in augment_train_gen(train_gen, additional_augmentation, visualize)
     46             imgs = seq.augment_images(imgs)
     47             print(type(imgs))
---> 48             imgs = np.asarray(imgs)    #np.uint8
     49             print(type(boxes))
     50             boxes = np.asarray(boxes)

~/anaconda3/envs/tf/lib/python3.6/site-packages/numpy/core/numeric.py in asarray(a, dtype, order)
    499 
    500     """
--> 501     return array(a, dtype, copy=False, order=order)
    502 
    503 

ValueError: could not broadcast input array from shape (818,1199,3) into shape (818)

Can you help on it?

Thanks a lot.

Liming

**Comment by kunwar31** [comment]
Thank you @liminghuiv 
Looks like you've made your own changes on the code as I can't reproduce this issue, please send the full definition of augment_train_gen

**Comment by liminghuiv** [comment]
Hi @kunwar31 ,
Have you ever run the part of visualize:
import matplotlib.pyplot as plt

skip_batches = 5
i = 0

for imgs,boxes in augment_train_gen(train_gen, additional_augmentation=True, visualize=True):
    if i > skip_batches:
        fig=plt.figure(figsize=(24,96))
        columns = 2
        rows = 8
        for i in range(1, columns*rows + 1):
            draw_boxes(imgs[i], boxes[i], (0, 255, 0), thickness=1)
            fig.add_subplot(rows, columns, i)
            plt.imshow(cv2.cvtColor(imgs[i],cv2.COLOR_BGR2RGB))
        plt.show()
        break
    else:
        i += 1
Thanks a lot.

Liming
