### ISSUE TITLE
Kernel keeps dying executing test_anchors.ipynb

### ISSUE THREAD

**Issue by SatyamGaba** [kunwar31/ESRI_Object_Detection#2]
When I executed the 3rd cell in test_anchors.ipynb, the kernel dies without throwing any error. 
`while run(valid_gen,args,parse_anchor_parameters(args.config)):
    pass`
I have tried it on both my local server and google colab.
What could be the reason and how to fix it?

**Comment by kunwar31** [comment]
This must be related to using OpenCV in a notebook,try running it in a python script and/or please check your OpenCV installation
