### ISSUE TITLE
Training Data?

### ISSUE THREAD

**Issue by orcaman** [kunwar31/ESRI_Object_Detection#3]
This is great, thanks for sharing. I'm wondering if the training data is available to download from somewhere so that I could replicate your results? Thanks!

**Comment by yexing99** [comment]
I also can't find the training data so I can't replicate the process. Any suggestions?

**Comment by kunwar31** [comment]
Hackerearth has removed the problem page - luckily someone on kaggle has hosted it - https://www.kaggle.com/kbhartiya83/swimming-pool-and-car-detection

**Comment by orcaman** [comment]
@kunwar31 thanks, you rock!
